use std::{env, fs, path::PathBuf};

fn main() {
    slint_build::compile("ui/app.slint").expect("compile UI");

    let root = PathBuf::from(env::var_os("CARGO_MANIFEST_DIR").expect("manifest directory"));
    let files = [
        ("WINWS2", "winws2.exe"),
        ("CYGWIN", "cygwin1.dll"),
        ("WINDIVERT", "WinDivert.dll"),
        ("WINDIVERT_DRIVER", "WinDivert64.sys"),
        ("ZAPRET_LIB", "lua/zapret-lib.lua"),
        ("ZAPRET_ANTIDPI", "lua/zapret-antidpi.lua"),
    ];
    let mut generated = String::from("// Generated by build.rs.\n");
    for (name, relative) in files {
        let path = root.join("runtime").join(relative);
        println!("cargo:rerun-if-changed={}", path.display());
        let path = path
            .canonicalize()
            .unwrap_or_else(|_| panic!("missing bundled runtime file: {}", path.display()));
        generated.push_str(&format!(
            "pub static {name}: &[u8] = include_bytes!({path:?});\n"
        ));
    }
    let output =
        PathBuf::from(env::var_os("OUT_DIR").expect("output directory")).join("bundled_runtime.rs");
    fs::write(output, generated).expect("write bundled runtime source");
}
